version: '3'
services:
  # mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/db_init:/docker-entrypoint-initdb.d
  # apache,php
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - .:/var/www/src:cached
    ports:
      - "80:80"
volumes:
  mysqldata: